INSERT INTO roles (id, name) VALUES (1, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, name) VALUES (2, 'USER') ON CONFLICT DO NOTHING;

INSERT INTO priorities (id, name) VALUES (1, 'NORMAL') ON CONFLICT DO NOTHING;
INSERT INTO priorities (id, name) VALUES (2, 'MEDIA') ON CONFLICT DO NOTHING;
INSERT INTO priorities (id, name) VALUES (3, 'ALTA') ON CONFLICT DO NOTHING;
