services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container_api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRESQL_DATABASE: test_db