services:
  mysql:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123